[package]
name = "did_resolver_registry"
version = "0.1.0"
edition = "2021"

[dependencies]
did_resolver = { path = "../did_resolver" }

[dev-dependencies]
tokio = { version = "1.27.0", default-features = false, features = ["macros", "rt"] }
mockall = "0.11.4"
async-trait = "0.1.68"
