# For details on how this file works refer to:
#   - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Check for updates once a week
  #  - Group all updates into a single PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns: ["*"]

  # Maintain dependencies for Cargo Packages
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/aries/misc/anoncreds_types"
      - "/aries/agents/aries-vcx-agent"
      - "/aries/agents/mediator"
      - "/aries/agents/aath-backchannel"
      - "/aries/aries_vcx"
      - "/aries/aries_vcx_anoncreds"
      - "/aries/aries_vcx_ledger"
      - "/aries/aries_vcx_wallet"
      - "/aries/messages"
      - "/aries/messages_macros"
      - "/did_core/did_doc"
      - "/did_methods"
      - "/did_parser_nom"
      - "/did_resolver"
      - "/did_resolver_registry"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directories:
      - "/.github/ci"
      - "/aries/agents/aath-backchannel"
      - "/aries/agents/mediator"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
