[package]
name = "aries-vcx-backchannel"
version = "0.1.0"
edition = "2018"
authors = [
    "Absa Group Limited",
    "Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>",
]
description = "Backchannel for aries-vcx"

[dependencies]
derive_more = { workspace = true, features = [
    "from",
    "try_into",
    "display",
    "error",
] }
actix-web = "4"
clap = { version = "4.5.6", features = ["derive"] }
reqwest = { workspace = true, features = ["json", "multipart", "blocking"] }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
uuid = { workspace = true, features = ["serde"] }
aries-vcx-agent = { path = "../../../aries/agents/aries-vcx-agent" }
anoncreds_types = { path = "../../../aries/misc/anoncreds_types" }
display_as_json = { path = "../../../misc/display_as_json" }

[profile.release]
debug = 0
panic = 'unwind'
incremental = false
