FROM alpine:3.15.4 AS builder

ARG UID=1000
ARG GID=1000
RUN addgroup -g $GID indy && adduser -u $UID -D -G indy indy

RUN apk update && apk upgrade && \
    apk add --no-cache \
        build-base \
        curl \
        openssl-dev \
        zeromq-dev

USER indy
WORKDIR /home/indy

ARG RUST_VER="1.74.1"
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VER --default-host x86_64-unknown-linux-musl
ENV PATH="/home/indy/.cargo/bin:$PATH" RUSTFLAGS="-C target-feature=-crt-static"

USER root
RUN chown -R indy:indy .
USER indy

RUN cargo new --bin aries-vcx-backchannel
WORKDIR ./aries-vcx-backchannel
COPY --chown=indy:indy ./aries-vcx/Cargo.lock ./aries-vcx/Cargo.toml ./
RUN cargo build

FROM alpine:3.15.4

ARG UID=1000
ARG GID=1000
RUN addgroup -g $GID indy && adduser -u $UID -D -G indy indy

RUN apk update && apk upgrade && \
    apk add --no-cache \
        openssl-dev \
        zeromq-dev

RUN mkdir /resource
COPY --from=builder /home/indy/aries-vcx-backchannel/target/debug/aries-vcx-backchannel .
ENTRYPOINT ["./aries-vcx-backchannel"]
