FROM alpine:3.20.1 AS builder

ARG UID=1000
ARG GID=1000
RUN addgroup -g $GID aries && adduser -u $UID -D -G aries aries

RUN apk update && apk upgrade && \
    apk add --no-cache \
        build-base \
        curl \
        openssl-dev \
        zeromq-dev

USER aries
WORKDIR /home/aries

ARG RUST_VER="1.79.0"
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_VER --default-host x86_64-unknown-linux-musl
ENV PATH="/home/aries/.cargo/bin:$PATH" RUSTFLAGS="-C target-feature=-crt-static"

USER root
RUN chown -R aries:aries .
USER aries

COPY --chown=aries:aries . vcx
WORKDIR /home/aries/vcx
RUN cargo build --bin aries-vcx-backchannel

FROM alpine:3.20.1

ARG UID=1000
ARG GID=1000
RUN addgroup -g $GID aries && adduser -u $UID -D -G aries aries

RUN apk update && apk upgrade && \
    apk add --no-cache \
        openssl-dev \
        zeromq-dev

RUN mkdir /resource
COPY --from=builder /home/aries/vcx/target/debug/aries-vcx-backchannel .
ENTRYPOINT ["./aries-vcx-backchannel"]
