name: "setup-testing-nodejs"
description: 'Install library deps, build libvcx'

runs:
  using: "composite"
  steps:
    - name: Use Node.js 12
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.64.0
    - uses: Swatinem/rust-cache@v2
    - name: "Install dependencies"
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libsodium-dev libssl-dev libzmq3-dev
    - name: "Build libvcx"
      shell: bash
      run: |
        cargo build --manifest-path="libvcx/Cargo.toml"
        sudo cp "target/debug/libvcx.so" /usr/lib
    - name: "Transpile TS wrapper"
      shell: bash
      run: (cd wrappers/node && npm install && npm run tscversion && npm run compile)