[package]
name = "did_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
once_cell = "1.17.1"
ouroboros = "0.15.6"
regex = "1.7.3"
serde = "1.0.160"
