[package]
name = "indy-ledger-response-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
time = "0.3.20"
indy-vdr.workspace = true
thiserror = "1.0.44"
anoncreds-clsignatures = "0.3.2"
