[package]
name = "indy-ledger-response-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
indy-vdr.workspace = true
thiserror.workspace = true
anoncreds-clsignatures.workspace = true
