[package]
name = "did_parser_nom"
version = "0.1.0"
edition = "2021"

[dependencies]
nom.workspace = true
serde.workspace = true
log.workspace = true
percent-encoding.workspace = true

[dev-dependencies]
serde_test.workspace = true
env_logger.workspace = true
