[package]
name = "did_parser_nom"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
serde.workspace = true
log = "0.4.16"
percent-encoding = "2"

[dev-dependencies]
serde_test = "1.0.176"
env_logger = "0.11.3"
