[package]
name = "shared"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
lazy_static.workspace = true
regex.workspace = true
thiserror.workspace = true
bs58.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
reqwest.workspace = true
log.workspace = true
