[package]
name = "messages"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
serde = { version = "1.0.167", features = ["derive"] }
chrono = { version = "0.4.23", features = ["serde"] }
lazy_static = "1.3"
serde_json = "1.0.100"
url = { version = "2.3", features = ["serde"] }
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.37"
derive_more = "0.99.17"
transitive = "0.5.0"
isolang = { version = "2.2.0" }
typed-builder = "0.16.0"
messages_macros = { path = "../messages_macros" }
diddoc_legacy = { path = "../misc/legacy/diddoc_legacy" }
shared = { path = "../misc/shared" }
did_parser = { path = "../../did_core/did_parser" }
did_doc_sov = { path = "../../did_core/did_doc_sov" }
display_as_json = { path = "../../misc/display_as_json" }
