name: 'detect-skip-info'
description: Determine parts of CI to be skipped

outputs:
  skip-tests-e2e:
    description: "True if CI should skip E2E testing"
    value: ${{ steps.main.outputs.skip-tests-e2e }}

runs:
  using: "composite"
  steps:
    - name: "Detect skip job tags"
      id: 'main'
      shell: bash
      run: |
        if [[ "${{ contains(github.event.pull_request.labels.*.name, 'skip-ios') }}" == "true" ]]; then
          echo "Detected tag to skip E2E tests"
          echo "skip-ios=true" >> $GITHUB_OUTPUT
        fi;
        if [[ "${{ contains(github.event.pull_request.labels.*.name, 'skip-android') }}" == "true" ]]; then
          echo "Detected tag to skip E2E tests"
          echo "skip-android=true" >> $GITHUB_OUTPUT
        fi;
        
        echo "Finished, GITHUB_OUTPUT:\n`cat $GITHUB_OUTPUT`"
