name: 'detect-skip-info'
description: Determine parts of CI to be skipped

outputs:
  skip-ios:
    description: "True if CI should skip IOS build/testing"
    value: ${{ steps.main.outputs.skip-ios }}
  skip-android:
    description: "True if CI should skip Android build/testing"
    value: ${{ steps.main.outputs.skip-android }}
  skip-napi-m1:
    description: "True if CI should skip IOS build/testing"
    value: ${{ steps.main.outputs.skip-ios }}
  skip-ci:
    description: "True if CI should skip Android build/testing"
    value: ${{ steps.main.outputs.skip-android }}


runs:
  using: "composite"
  steps:
    - name: "Detect skip job tags"
      id: 'main'
      shell: bash
      run: |
        if [[ "${{ contains(github.event.pull_request.labels.*.name, 'skip-ci') }}" == "true" ]]; then
          echo "Detected tag to skip ios"
          echo "skip-ci=true" >> $GITHUB_OUTPUT
          echo "skip-ios=true" >> $GITHUB_OUTPUT
          echo "skip-android=true" >> $GITHUB_OUTPUT
          echo "skip-napi-m1=true" >> $GITHUB_OUTPUT
        fi

        if [[ "${{ contains(github.event.pull_request.labels.*.name, 'skip-ios') }}" == "true" ]]; then
          echo "Detected tag to skip ios"
          echo "skip-ios=true" >> $GITHUB_OUTPUT
        fi

        if [[ "${{ contains(github.event.pull_request.labels.*.name, 'skip-android') }}" == "true" ]]; then
          echo "Detected tag to skip android"
          echo "skip-android=true" >> $GITHUB_OUTPUT
        fi;

        if [[ "${{ contains(github.event.pull_request.labels.*.name, 'skip-napi-m1') }}" == "true" ]]; then
          echo "Detected tag to skip M1 napi build"
          echo "skip-napi-m1=true" >> $GITHUB_OUTPUT
        fi;

        echo "Finished, GITHUB_OUTPUT:\n`cat $GITHUB_OUTPUT`"
