[package]
name = "mediator-client"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
messages = { path = "../../messages" }
reqwest = { version = "0.12", features = ["json"] }
thiserror = "1.0"
serde = "1.0"
url = "2.5.0"
