[package]
name = "did_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.160"
shared = { path = "../../aries/misc/shared" } # TODO: Remove as soon as migration to qualified DIDs is complete
