name: "setup-codecov-rust"
description: 'Setup host environment for measuring rust code coverage'

inputs:
  skip-docker-setup:
    description: 'If true, skip spinning up docker containers'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: Swatinem/rust-cache@v2
    - name: "Install dependencies"
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libsodium-dev libssl-dev libzmq3-dev
        cargo install grcov --version 0.8.9
    - name: "Setup environment"
      if: ${{ inputs.skip-docker-setup != 'true' }}
      shell: bash
      run: |
        docker run --rm -d --name mysql     --network host -e MYSQL_ROOT_PASSWORD=mysecretpassword mysql:5.7.35
        docker run --rm -d --name indypool  --network host ${{ env.DOCKER_IMAGE_POOL }}
        sleep 5
        docker-compose -f ./ci/agency/docker-compose.yml up -d