name: 'publish-napi'
description: |
  Publishes vcx-napi-rs node packages

inputs:
  publish-version:
    required: true
  npmjs-token:
    required: true
  node-version:
    default: 18

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ github.workspace }}/wrappers/vcx-napi-rs/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: ${{ github.workspace }}/wrappers/vcx-napi-rs
      shell: bash
    - name: Download napi artifacts
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}/wrappers/vcx-napi-rs/artifacts
    - name: Move artifacts
      run: |
        find . -type d -not -path \*\*/artifacts/bindings-\* -path \*\*/artifacts/\*\* -mindepth 2 -maxdepth 2 -exec rm -rf {} \+
        ls -R artifacts
        npm run artifacts
      working-directory: ${{ github.workspace }}/wrappers/vcx-napi-rs
      shell: bash
    - name: Publish
      run: |
        if [[ "$PUBLISH_VERSION" ]]
        then
          npm set "//registry.npmjs.org/:_authToken" $NPMJS_TOKEN
          npm version $PUBLISH_VERSION
          npm run prepublish
          npm publish
        else
           echo "New version was not defined, skipping release."
        fi
      working-directory: ${{ github.workspace }}/wrappers/vcx-napi-rs
      shell: bash
      env:
        NPMJS_TOKEN: ${{ inputs.npmjs-token }}
        PUBLISH_VERSION: ${{ inputs.publish-version }}
