name: "start-vcxs"
description: 'Startup services need for testing, load up testing image'

inputs:
  docker-img:
    description: 'libvcx tester image to pull'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Load libvcx tester image"
      uses: ./.github/actions/load-image
      with:
        docker-img: ${{ inputs.docker-img }}
    - name: "Start indypool, mysql, agency"
      shell: bash
      run: |
        set -x
        docker run --rm -d --name mysql     --network host -e MYSQL_ROOT_PASSWORD=mysecretpassword mysql:5.7.35
        docker run --rm -d --name indypool  --network host ${{ env.DOCKER_IMAGE_POOL }}
        sleep 5
        docker-compose -f ./ci/agency/docker-compose.yml up -d
        sleep 10
