[package]
name = "did_resolver_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
did_resolver = { path = "../did_resolver" }
async-trait = "0.1.68"
serde_json = "1.0.96"
thiserror = "1.0.40"
hyper = { version = "0.14.26", features = ["client", "http2"] }
hyper-tls = "0.5.0"

[dev-dependencies]
hyper = { version = "0.14.26", features = ["server"] }
tokio = { version = "1.27.0", default-features = false, features = ["macros", "rt"] }
tokio-test = "0.4.2"
