[package]
name = "indy-api-types"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
futures = { version = "0.3", default-features = false, features = ["std"] }
log = { version = "0.4", features = ["std"] }
libc = "0.2"
serde = "1"
serde_json = "1"
serde_derive = "1"
openssl = { version = "0.10" }
bs58 = "0.5"
sqlx = { version = "0.7", features = [ "sqlite", "mysql", "runtime-tokio-rustls" ] }
ursa = { version = "0.3.7", default-features = false, features = ["wasm"] }