[package]
name = "vcx-napi-rs"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "vcx_napi_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]
doctest = false

[features]
test_utils = [ "libvcx/test_utils" ]

[dependencies]
libvcx = { path = "../../libvcx", default-features = false }
log = "0.4.16"
napi = { version = "=2.9.1", default-features = false, features = [ "async" ] }
napi-derive = { version = "=2.9.3" }

[build-dependencies]
napi-build = "2.0.1"
