[package]
name = "vcx-napi-rs"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "vcx_napi_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]
doctest = false

[features]
default = ["ledger_vdrtools", "anoncreds_vdrtools"]

ledger_indyvdr = ["libvcx_core/ledger_indyvdr"]
ledger_vdrtools = ["libvcx_core/ledger_vdrtools"]

anoncreds_credx = ["libvcx_core/anoncreds_credx"]
anoncreds_vdrtools = ["libvcx_core/anoncreds_vdrtools"]

[dependencies]
libvcx_core = { path = "../../libvcx_core"  }
wallet_migrator = { path = "../../wallet_migrator" }
log = "0.4.16"
napi = { version = "2.10.14", default-features = false, features = [ "async" ] }
napi-derive = { version = "2.10.1" }
uuid = { version = "0.8", default-features = false, features = ["v4"] }
chrono = "0.4.23"

[build-dependencies]
napi-build = "2.0.1"
