/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function createOutOfBand(config: string): number
export function createOutOfBandMsgFromMsg(msg: string): number
export function appendMessage(handle: number, msg: string): void
export function appendService(handle: number, service: string): void
export function appendServiceDid(handle: number, did: string): void
export function extractA2AMessage(handle: number): string
export function toA2AMessage(handle: number): string
export function connectionExists(handle: number, connHandles: Array<number>): Promise<number>
export function buildConnection(handle: number): Promise<string>
export function getThreadIdSender(handle: number): string
export function getThreadIdReceiver(handle: number): string
export function toStringSender(handle: number): string
export function toStringReceiver(handle: number): string
export function fromStringSender(oobData: string): number
export function fromStringReceiver(oobData: string): number
export function releaseSender(handle: number): void
export function releaseReceiver(handle: number): void
