[package]
name = "aries-vcx-agent"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
aries_vcx = { path = "../../aries_vcx" }
aries_vcx_wallet = { path = "../../aries_vcx_wallet", features = [
    "askar_wallet",
] }
aries_vcx_anoncreds = { path = "../../aries_vcx_anoncreds", features = ["anoncreds"] }
aries_vcx_ledger = { path = "../../aries_vcx_ledger"}
anoncreds_types = { path = "../../misc/anoncreds_types" }
shared = { path = "../../misc/shared" }
did_resolver_registry = { path = "../../../did_core/did_resolver_registry" }
did_resolver_sov = { path = "../../../did_core/did_methods/did_resolver_sov" }
did_peer = { path = "../../../did_core/did_methods/did_peer" }
did_key = { path = "../../../did_core/did_methods/did_key" }
public_key = { path = "../../../did_core/public_key" }
async-trait.workspace = true
log.workspace = true
uuid.workspace = true
thiserror.workspace = true
url = { workspace = true, features = ["serde"] }
display_as_json = { path = "../../../misc/display_as_json" }
