name: Build and push napi image

on:
  workflow_dispatch:
    inputs:
      image-type:
        description: 'Docker image type'
        required: true
        type: choice
        options:
          - alpine
          - debian

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: "Git checkout"
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build image"
        run: |
          docker build -f aries/wrappers/vcx-napi-rs/${{ inputs.image-type }}.Dockerfile  -t ghcr.io/hyperledger/aries-vcx/napi-rs-${{ inputs.image-type }}:latest .
      - name: "Push image to ghcr.io"
        run: |
          docker push ghcr.io/hyperledger/aries-vcx/napi-rs-${{ inputs.image-type }}:latest
